import type { GameCharacter } from './types';

const main = (character: Omit<GameCharacter, 'tier' | 'stayNights'>): GameCharacter => ({
  ...character, tier: 'main', stayNights: [2, 4], portrait: `/portraits/${character.id}.png`,
});

export const mainCharacters: GameCharacter[] = [
  main({ id: 'hunter', name: 'The Hunter', kind: 'human', personality: 'blunt, watchful, economical with words', appearance: 'scarred hunter gripping a worn rifle sling', backstory: 'He has tracked the things since his brother vanished on the northern ridge.', dialogue: ['Tracks doubled back without turning. Something followed me.', 'Keep the lamp low. It notices confidence.'], inspections: ['Pine resin masks old blood on his cuffs.', 'His map marks this cabin as SAFE?'], behaviors: ['Checks every lock twice.', 'Answers in clipped sentences.'], outcome: 'peaceful', knows: ['old-woman', 'lumberjack'] }),
  main({ id: 'old-woman', name: 'The Old Woman', kind: 'human', personality: 'warm, grandmotherly, quietly ominous', appearance: 'elderly woman wrapped in a black wool shawl', backstory: 'She once owned the cabin and says its walls remember every lie.', dialogue: ['There you are, dear. Let an old woman thaw before her bones start arguing.', 'Snow lies beautifully. People rarely manage it so well.'], inspections: ['Her shawl is strangely dry.', 'A brass cabin key hangs at her throat.'], behaviors: ['Mends torn clothes by the fire.', 'Calls frightened guests “my chick.”'], outcome: 'peaceful', knows: ['hunter', 'priest'] }),
  main({ id: 'doctor', name: 'The Doctor', kind: 'human', personality: 'clinical, tired, compassionate under pressure', appearance: 'bespectacled doctor carrying a battered medical satchel', backstory: 'He treated a patient whose heartbeat continued in an empty bed.', dialogue: ['My fingers still work. That makes me useful, if not trustworthy.', 'Symptoms first, theories later. Panic reverses that order.'], inspections: ['His instruments are clean but his cuffs are not.', 'He watches your pupils while speaking.'], behaviors: ['Takes everyone’s pulse without asking.', 'Describes fear as a symptom.'], outcome: 'peaceful', knows: ['teacher', 'soldier'] }),
  main({ id: 'woman-red', name: 'The Woman in Red', kind: 'human', personality: 'guarded, perceptive, dryly defiant', appearance: 'pale young woman in a weather-beaten red coat', backstory: 'She escaped the lodge after hearing her own voice invite people downstairs.', dialogue: ['Do not ask why the coat is red. Ask why the snow behind me is.', 'I know how suspicion looks. I wore it here.'], inspections: ['Black thread repairs every pocket.', 'She holds one gloved fist closed.'], behaviors: ['Studies reflections instead of faces.', 'Never sits with her back to stairs.'], outcome: 'peaceful', knows: ['photographer'] }),
  main({ id: 'priest', name: 'The Priest', kind: 'skinwalker', personality: 'kind, calm, unnervingly flawless', appearance: 'soft-eyed priest in a dark snow-covered coat', backstory: 'Something memorized a priest’s final sermon but never learned doubt.', dialogue: ['Peace be with this house. You may take your time deciding.', 'Fear is only faith facing the wrong direction.'], inspections: ['His cross hangs backward.', 'Snow on his shoulders never melts.'], behaviors: ['Comforts people with exactly the words they want.', 'Never forgets a prayer or takes a breath.'], knows: ['old-woman'] }),
  main({ id: 'lost-boy', name: 'The Lost Boy', kind: 'human', personality: 'nervous, earnest, easily startled', appearance: 'shivering boy in an oversized black parka', backstory: 'He hid beneath a school bus while something called him in his teacher’s voice.', dialogue: ['I did what she said—I stayed by the road—but the road moved.', 'Please do not make me say it louder. It hears names.'], inspections: ['His glasses are taped at one hinge.', 'Homework pages line his sleeves.'], behaviors: ['Counts doors when frightened.', 'Stops mid-sentence to listen.'], outcome: 'peaceful', knows: ['teacher', 'student'] }),
  main({ id: 'lumberjack', name: 'The Lumberjack', kind: 'human', personality: 'rough, dependable, deeply superstitious', appearance: 'broad lumberjack in a fur-collared coat', backstory: 'He felled a tree that bled warm and whispered his daughter’s name.', dialogue: ['Got an axe, bad knees, and no patience left for talking trees.', 'Wood tells you before it breaks. People should learn that courtesy.'], inspections: ['Fresh sap stains his knuckles black.', 'His axe blade is wrapped in prayer ribbon.'], behaviors: ['Touches beams to feel vibrations.', 'Carves warding marks under chairs.'], outcome: 'peaceful', knows: ['hunter'] }),
  main({ id: 'teacher', name: 'The Teacher', kind: 'human', personality: 'measured, observant, quietly grieving', appearance: 'young teacher with round glasses and a notebook', backstory: 'She led her class from a stranded bus, then returned for the two children missing.', dialogue: ['I kept them singing so no copied voice could separate us.', 'Please ask one question at a time. Facts are shelter too.'], inspections: ['A child-size mitten is tucked in her coat.', 'Her attendance book has two wet names.'], behaviors: ['Corrects contradictions gently.', 'Takes attendance whenever someone enters.'], outcome: 'peaceful', knows: ['lost-boy', 'student', 'doctor'] }),
  main({ id: 'fisherman', name: 'The Fisherman', kind: 'human', personality: 'weathered, laconic, fatalistic', appearance: 'old fisherman in an iced wool cap', backstory: 'He pulled a second version of himself from beneath the frozen reservoir.', dialogue: ['Lake gave back what it never took. I left before it asked payment.', 'Deep water and deep snow keep the same secrets.'], inspections: ['Fishing line cuts circle his palms.', 'His coat smells of salt far from any sea.'], behaviors: ['Speaks in low, spare proverbs.', 'Listens to pipes like running water.'], outcome: 'peaceful' }),
  main({ id: 'musician', name: 'The Musician', kind: 'human', personality: 'wry, restless, lyrical without being sentimental', appearance: 'young musician carrying a battered guitar case', backstory: 'The forest answered his melody one note before he played it.', dialogue: ['My encore learned itself and followed me offstage.', 'Silence has rhythm tonight. Listen where it stumbles.'], inspections: ['One guitar string is tied around his wrist.', 'His fingertips are split and blue.'], behaviors: ['Taps rhythms when lying would be easier.', 'Identifies copied voices by cadence.'], outcome: 'peaceful', knows: ['student'] }),
  main({ id: 'student', name: 'The Student', kind: 'human', personality: 'curious, skeptical, brave by accident', appearance: 'young student with a canvas bag of books', backstory: 'She found tomorrow’s date written throughout a library book in her handwriting.', dialogue: ['I have three explanations. Unfortunately, impossible is winning.', 'The margins knew who would knock next. I tore that page out.'], inspections: ['Ink covers her left thumb.', 'Her notebook skips every thirteenth page.'], behaviors: ['Tests stories with precise questions.', 'Writes probabilities beside guests’ names.'], outcome: 'peaceful', knows: ['teacher', 'musician'] }),
  main({ id: 'photographer', name: 'The Photographer', kind: 'human', personality: 'intense, skeptical, compulsively honest', appearance: 'exhausted photographer with a camera harness', backstory: 'His last photograph showed an extra figure standing behind the camera.', dialogue: ['The lens sees details my fear edits out.', 'I took one picture of her red coat. Two women appeared.'], inspections: ['His camera contains no film.', 'Flash burns mark one glove.'], behaviors: ['Frames every doorway with his hands.', 'Distrusts anyone absent from reflections.'], outcome: 'peaceful', knows: ['woman-red'] }),
  main({ id: 'twin-sisters', name: 'The Twin Sisters', kind: 'human', personality: 'synchronized, playful, unsettling but loyal', appearance: 'two pale sisters in matching dark coats', backstory: 'They survived by splitting every sentence so nothing could copy either one whole.', dialogue: ['Mira: We are two people. Vera: Ask twice if you need proof.', 'Mira: One of us lies. Vera: Only about cards.'], inspections: ['Only one sister leaves clear footprints.', 'They share a single pair of red gloves.'], behaviors: ['Finish warnings, never jokes.', 'Sleep facing opposite directions.'], outcome: 'peaceful', knows: ['lost-boy'] }),
  main({ id: 'soldier', name: 'The Soldier', kind: 'human', personality: 'formal, cautious, disciplined', appearance: 'battle-worn soldier in a snow-caked field jacket', backstory: 'Her convoy returned with one extra passenger and no tire tracks.', dialogue: ['State the rules of entry. I will comply or withdraw.', 'Trust is not a feeling. It is a risk assessment.'], inspections: ['Every insignia has been removed.', 'Her flare pistol is unloaded.'], behaviors: ['Maps exits before sitting.', 'Assigns watches in exact shifts.'], outcome: 'peaceful', knows: ['doctor'] }),
  main({ id: 'wanderer', name: 'The Wanderer', kind: 'skinwalker', personality: 'mysterious, oblique, almost gentle', appearance: 'gaunt wanderer half-hidden by wet black hair', backstory: 'No village remembers him, yet old maps mark his route as a moving border.', dialogue: ['I came from the direction that disappears when named.', 'Your door is not between inside and outside. Not tonight.'], inspections: ['His footprints begin at the porch.', 'His shadow points toward the moon.'], behaviors: ['Answers questions with truthful riddles.', 'Watches places where walls almost meet.'] }),
];
